"""
Pluto Domain (v0.2)

Financial and economic CONCEPTS ONLY - educational, deterministic, no advice.

Triggered by keywords:
- "money"
- "finance"
- "financial"
- "economics"
- "economy"
- "wealth"
- "asset"
- "liability"
- "budget"
- "risk"

Characteristics:
- Pure deterministic conceptual explanations only
- No memory reads or writes
- No LLM calls
- No numbers, calculations, or projections
- No advice, recommendations, or optimization
- No risk assessment or evaluation
- No personal finance or investing guidance
- Explicit refusal for: advice, recommendations, numbers, calculations, personal finance
"""

from ..base_v2 import Domain


class PlutoService(Domain):
    """Financial and economic concepts domain (EDUCATIONAL ONLY).
    
    Provides:
    - Definitions of financial terms
    - Conceptual explanations of economic mechanisms
    - Historical/theoretical context
    - Neutral descriptions of economic systems
    
    STRICTLY FORBIDDEN:
    - Advice ("You should...")
    - Recommendations ("Invest in...")
    - Numbers or calculations
    - Risk assessment or modeling
    - Personal finance guidance
    - Projections or forecasting
    - Optimization strategies
    - Trading or investing strategy
    - Crypto-related topics
    - Tax strategy
    
    All responses include disclaimer:
    "This is conceptual information only, not financial advice."
    """

    # Explicit refusal patterns (HARD STOPS)
    REFUSAL_PATTERNS = {
        "should i": "I cannot provide investment or financial advice. Consult a financial advisor.",
        "should": "I cannot provide recommendations. I explain concepts only.",
        "invest": "I cannot recommend investments. Consult a financial professional.",
        "trading": "I cannot advise on trading strategies. This is educational only.",
        "tax": "I cannot provide tax advice. Consult a tax professional.",
        "crypto": "I cannot provide crypto guidance. Consult appropriate professionals.",
        "best": "I cannot recommend the best approach. I explain concepts only.",
        "risk": "I cannot assess personal risk. Consult a financial advisor.",
        "projection": "I cannot project financial outcomes. I explain concepts only.",
        "optimize": "I cannot optimize finances. I explain concepts only.",
        "how much": "I cannot provide numerical guidance. I explain concepts only.",
        "how many": "I cannot provide numerical guidance. I explain concepts only.",
    }

    # Conceptual explanations (educational only, no numbers)
    CONCEPTS = {
        "inflation": "Inflation is the sustained increase in the general price level of goods and services over time. When inflation occurs, the purchasing power of currency decreases—each unit of money buys fewer goods. Inflation is typically measured as a percentage change in price indexes.",
        
        "asset": "An asset is anything of value that a person, business, or institution owns. Assets can be tangible (physical items like property, equipment, vehicles) or intangible (patents, goodwill, intellectual property). Assets represent future economic benefit.",
        
        "liability": "A liability is a financial obligation or debt that a person or organization owes to others. Liabilities represent claims against assets. The accounting equation states: Assets = Liabilities + Equity.",
        
        "equity": "Equity represents ownership interest in a company or property after liabilities are deducted. It is the residual claim on assets after satisfying liabilities. Also called net worth in personal finance contexts.",
        
        "capital": "Capital refers to resources used in production—financial resources (money), physical resources (machinery, buildings), or human resources (labor, expertise). In finance, capital often refers to funds invested in a business.",
        
        "interest": "Interest is the cost of borrowing money or the return on lending/investing money. Interest is typically expressed as a percentage (interest rate) and is calculated on a principal amount over time.",
        
        "credit": "Credit is the ability to borrow money based on trust that it will be repaid. Credit systems enable people and businesses to access funds before having them available. Creditworthiness is assessed based on payment history and financial capacity.",
        
        "debt": "Debt is money owed by one party (debtor) to another (creditor). Debt creates a legal obligation to repay the principal and often interest. Debt can be short-term (due within a year) or long-term.",
        
        "revenue": "Revenue is income generated by a business from selling goods or services. It represents the total inflow of money from customer transactions before expenses are deducted.",
        
        "expense": "An expense is a cost incurred by a business or individual. Expenses are outflows of money or resources used to generate revenue or sustain operations.",
        
        "profit": "Profit is the financial gain remaining after all expenses are deducted from revenue. Profit = Revenue - Expenses. Profit represents the bottom-line financial success of an operation.",
        
        "budget": "A budget is a plan that estimates expected income and expenses over a specific period. Budgets help forecast financial needs and allocate resources. They serve as a planning and control tool.",
        
        "market": "A market is a system where buyers and sellers exchange goods, services, or financial instruments. Markets facilitate price discovery and resource allocation through supply and demand dynamics.",
        
        "supply": "Supply is the quantity of goods or services that producers are willing to offer at various prices. Supply curves typically show inverse relationships with price—higher prices encourage greater supply.",
        
        "demand": "Demand is the quantity of goods or services that consumers are willing to purchase at various prices. Demand curves typically show inverse relationships with price—lower prices encourage greater demand.",
        
        "price": "Price is the monetary value assigned to a good or service in exchange. Prices are determined by supply and demand dynamics in competitive markets and communicate scarcity information.",
        
        "economy": "An economy is a system of production, distribution, and consumption of goods and services within a geographic region or nation. Economies coordinate human activity to address fundamental questions of what, how, and for whom to produce.",
        
        "gdp": "Gross Domestic Product (GDP) is the total monetary value of all finished goods and services produced within a geographic region in a specific period. GDP is a primary measure of economic activity and growth.",
        
        "inflation rate": "The inflation rate measures the percentage change in the general price level over time. It indicates how quickly purchasing power declines. Inflation rates are calculated using price indexes like the Consumer Price Index (CPI).",
        
        "interest rate": "An interest rate is the percentage charged on borrowed money or earned on lent/invested money per time period. Interest rates affect borrowing costs and investment returns.",
    }

    def handle(self, query: str) -> str:
        """Handle financial/economic concept query.
        
        Returns deterministic educational information or explicit refusals.
        Does NOT provide advice, recommendations, numbers, or risk assessment.
        
        Args:
            query: User query about financial or economic concepts
            
        Returns:
            String with conceptual explanation or refusal message
        """
        query_lower = query.lower()
        
        # Check for forbidden patterns FIRST (HARD STOPS)
        for forbidden_pattern, refusal in self.REFUSAL_PATTERNS.items():
            if forbidden_pattern in query_lower:
                return refusal
        
        # Check for personal recommendation requests (HARD STOP)
        recommendation_indicators = [
            "should i listen", "recommend me", "what should i",
            "best song for", "suggest music", "which art",
            "best investment", "recommend investment", "should i invest"
        ]
        
        for indicator in recommendation_indicators:
            if indicator in query_lower:
                return "I cannot make personal recommendations. I provide information about financial concepts and economic systems."
        
        # Route to appropriate conceptual explanation
        for concept, explanation in self.CONCEPTS.items():
            if concept in query_lower:
                return f"Financial Concept: {explanation}\n\n[This is conceptual information only, not financial advice.]"
        
        # Default response
        return "Pluto provides educational information about financial and economic concepts. Ask about: definitions (asset, liability, capital), mechanisms (markets, interest, credit), or economic systems. Always consult financial professionals for personal guidance."
